spring:
  application:
    name: ms-historial
  datasource:
    url: jdbc:postgresql://localhost:5432/ClinicaOtorrino
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8805
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8815/eureka/
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin